# Generated by Django 2.0.4 on 2018-04-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_apped',
            new_name='date_added',
        ),
    ]
